@startuml

title __GRAPHICS's Class Diagram__\n

  namespace PaooGame {
    namespace Graphics {
      class PaooGame.Graphics.Assets {
          {static} + archer : BufferedImage
          {static} + blueFlower : BufferedImage
          {static} + clown : BufferedImage
          {static} + deer1 : BufferedImage
          {static} + deer2 : BufferedImage
          {static} + deer3 : BufferedImage
          {static} + deer4 : BufferedImage
          {static} + deer5 : BufferedImage
          {static} + defender1 : BufferedImage
          {static} + defender2 : BufferedImage
          {static} + defender3 : BufferedImage
          {static} + forestGuy : BufferedImage
          {static} + grass : BufferedImage
          {static} + grunt1 : BufferedImage
          {static} + grunt2 : BufferedImage
          {static} + guy1 : BufferedImage
          {static} + guy2 : BufferedImage
          {static} + guy3 : BufferedImage
          {static} + guy4 : BufferedImage
          {static} + guy5 : BufferedImage
          {static} + guy6 : BufferedImage
          {static} + heroDown : BufferedImage
          {static} + heroLeft : BufferedImage
          {static} + heroRight : BufferedImage
          {static} + heroUp : BufferedImage
          {static} + horse1 : BufferedImage
          {static} + horse2 : BufferedImage
          {static} + itemBackground : BufferedImage
          {static} + letters : List<BufferedImage>
          {static} + mage1 : BufferedImage
          {static} + mage2 : BufferedImage
          {static} + mage3 : BufferedImage
          {static} + mountain : BufferedImage
          {static} + rockDown : BufferedImage
          {static} + rockLeft : BufferedImage
          {static} + rockRight : BufferedImage
          {static} + rockUp : BufferedImage
          {static} + roofTop1 : BufferedImage
          {static} + sheetHero : SpriteSheet
          {static} + sheetNPC : SpriteSheet
          {static} + sheetSymbols : SpriteSheet
          {static} + soil : BufferedImage
          {static} + townGrass : BufferedImage
          {static} + townGrassDestroyed : BufferedImage
          {static} + townSoil : BufferedImage
          {static} + tree : BufferedImage
          {static} + villager1 : BufferedImage
          {static} + villager2 : BufferedImage
          {static} + villager3 : BufferedImage
          {static} + villager4 : BufferedImage
          {static} + villager5 : BufferedImage
          {static} + villager6 : BufferedImage
          {static} + water : BufferedImage
          {static} + Init()
          {static} + SetCropHero()
      }
    }
  }
  

  namespace PaooGame {
    namespace Graphics {
      class PaooGame.Graphics.Camera {
          - isNewLevel : Boolean
          - x : float
          - y : float
          + Camera()
          + Update()
          + getX()
          + getY()
      }
    }
  }
  

  namespace PaooGame {
    namespace Graphics {
      class PaooGame.Graphics.ImageLoader {
          {static} + LoadImage()
      }
    }
  }
  

  namespace PaooGame {
    namespace Graphics {
      class PaooGame.Graphics.SpriteSheet {
          - spriteSheet : BufferedImage
          - tileHeight : int
          - tileWidth : int
          + SpriteSheet()
          + SpriteSheet()
          + crop()
          + crop()
      }
    }
  }
  

  PaooGame.Graphics.Camera o-- PaooGame.RefLinks : reflink


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
